[package]
name = "wut-thesis"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Sebastian Górka", "Maciej Michalski"]
license = "MIT"
description = "Warsaw University of Technology thesis template for master's and bachelor's degrees"
repository = "https://github.com/bastyje/typst-wut-thesis-template"
keywords = ["thesis", "template", "typst", "Warsaw University of Technology"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"